language: go
go:
  - 1.7
env:
  - "PATH=/home/travis/gopath/bin:$PATH"
before_install:
  - go get github.com/mitchellh/gox
  - go get github.com/tcnksm/ghr
script:
  - go test -v ./...
after_success:
  - gox -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}"
  - ghr -u irccloud -t $GITHUB_TOKEN -replace -prerelease -draft pre-release dist/
